version: '3'

volumes:
  djstartproject_local_postgres_data: {}
  djstartproject_local_postgres_data_backups: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: djstartproject_local_django
    container_name: djstartproject_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'

    command: /start
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: djstartproject_production_postgres
    container_name: djstartproject_local_postgres
    volumes:
      - djstartproject_local_postgres_data:/var/lib/postgresql/data
      - djstartproject_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: djstartproject_local_redis
