version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: interintel_production_django
    volumes:
      - production_django_media:/app/modules/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: interintel_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: interintel_local_nginx
    # ports:
    #    - "81:81"
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
